#:schema node_modules/wrangler/config-schema.json

name = "neuraltruth-frontend"
main = ".open-next/worker.js"
compatibility_date = "2025-05-01"
compatibility_flags = ["nodejs_compat"]

# Static assets served from the .open-next/assets directory
[assets]
directory = ".open-next/assets"

# Environment variables available to the Worker at runtime
[vars]
GROQ_API_KEY = "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"
TAVILY_API_KEY = "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"
